"""
Business report generator.

Reads drift summaries and investigation reports to produce a concise
markdown health summary for stakeholders. No external LLM required.
"""

import json
import logging
import os
from datetime import datetime, timezone
from pathlib import Path

log = logging.getLogger(__name__)


def get_project_root() -> Path:
    return Path(__file__).resolve().parents[3]


def load_json(path: str) -> dict | None:
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return json.load(f)


def generate_report(
    reports_dir: str = None,
    output_dir: str = None,
) -> str:
    """Generate a daily/weekly summary report for business stakeholders."""
    project_root = get_project_root()
    reports_dir = reports_dir or str(project_root / "reports")
    output_dir = output_dir or reports_dir

    if not os.path.isabs(reports_dir):
        reports_dir = str(project_root / reports_dir)
    if not os.path.isabs(output_dir):
        output_dir = str(project_root / output_dir)

    os.makedirs(output_dir, exist_ok=True)

    log.info("Generating business summary report...")

    drift_check = load_json(os.path.join(reports_dir, "drift_check_result.json"))
    churn_summary = load_json(os.path.join(reports_dir, "churn_drift_summary.json"))
    fraud_summary = load_json(os.path.join(reports_dir, "fraud_drift_summary.json"))

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M")
    report = "# MLOps Platform: Weekly Health Report\n\n"
    report += f"- **Report Date**: {ts} UTC\n\n"
    report += "## Executive Summary\n\n"

    retrain_needed = drift_check.get("retrain_needed", {}) if drift_check else {}
    if retrain_needed.get("churn") or retrain_needed.get("fraud"):
        status = "Action Required"
        summary_text = (
            "Data drift was detected in one or more models, triggering an automated "
            "retraining cycle. The system is self-correcting, but performance may have "
            "been temporarily degraded."
        )
    else:
        status = "All Systems Normal"
        summary_text = (
            "All models are performing within expected parameters. No data drift was "
            "detected, and no manual intervention is required."
        )

    report += f"**Overall Status**: `{status}`\n\n"
    report += f"> {summary_text}\n\n"

    report += "## Customer Churn Prediction Model\n\n"
    if churn_summary:
        drifted = churn_summary.get("dataset_drift_detected", False)
        drift_share = churn_summary.get("drift_share", 0)
        if drifted:
            report += "- **Status**: `Warning`\n"
            report += (
                f"- **Details**: Data drift detected in **{drift_share:.1%}** of features. "
                "An automated retraining process has been initiated.\n"
            )
        else:
            report += "- **Status**: `Normal`\n"
            report += "- **Details**: The model is stable and performing as expected.\n"
    else:
        report += "- **Status**: `Unknown`\n"
        report += "- **Details**: No monitoring data available for the churn model.\n"

    report += "\n## Transaction Fraud Detection Model\n\n"
    if fraud_summary:
        drifted = fraud_summary.get("dataset_drift_detected", False)
        drift_share = fraud_summary.get("drift_share", 0)
        if drifted:
            report += "- **Status**: `Action Required`\n"
            report += (
                f"- **Details**: Significant data drift of **{drift_share:.1%}** detected. "
                "Retraining is in progress.\n"
            )
        else:
            report += "- **Status**: `Normal`\n"
            report += "- **Details**: The model is stable and performing as expected.\n"
    else:
        report += "- **Status**: `Unknown`\n"
        report += "- **Details**: No monitoring data available for the fraud model.\n"

    report += (
        "\n---\n"
        "*Automated report generated by the MLOps platform. "
        "For technical details, see the full drift reports in the reports directory.*\n"
    )

    report_path = os.path.join(output_dir, "business_summary.md")
    with open(report_path, "w") as f:
        f.write(report)

    log.info("Report saved to: %s", report_path)
    return report


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    generate_report()
